# Generated by Django 4.2.2 on 2024-01-09 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='discord_id',
            field=models.IntegerField(default=0, help_text='The discord ID.', unique=True),
            preserve_default=False,
        ),
    ]
