# Generated by Django 4.2.2 on 2024-01-09 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0002_players_discord_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='game_num',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
