# Generated by Django 4.2.2 on 2024-01-09 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0003_matches_game_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='discord_id',
            field=models.BigIntegerField(blank=True, help_text='The discord ID.', null=True, unique=True),
        ),
    ]
