# Generated by Django 4.2.2 on 2023-07-16 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('format', models.CharField(choices=[('single_elimination', 'Single Elimination'), ('double_elimination', 'Double Elimination'), ('round_robin', 'Round Robin'), ('swiss', 'Swiss System')], max_length=20)),
                ('start_date', models.DateField()),
                ('swiss_rounds', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
