# Generated by Django 4.2.2 on 2023-07-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0002_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
