# Generated by Django 4.2.2 on 2023-07-16 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0004_organizator_tournament_end_date_tournament_org'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournaments', to='engine.organizator'),
        ),
    ]
