# Generated by Django 4.2.2 on 2023-08-18 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_discord_alter_profile_telegram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='discord',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telegram',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='twitter',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
