# Generated by Django 4.2.2 on 2023-08-21 08:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_profile_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="static/avatars/default-avatar.jpg",
                null=True,
                upload_to="static/avatars/",
            ),
        ),
    ]
