# Generated by Django 4.2.2 on 2023-07-12 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaderboard", "0003_game_player_ratingperiod_playerstatsnode_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="player",
            options={"ordering": ["name", "id"]},
        ),
        migrations.AddField(
            model_name="matchupstatsnode",
            name="average_goals_against_per_game",
            field=models.FloatField(
                default=0,
                help_text="The average number of goals scored per game by player2.",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="playerstatsnode",
            name="average_goals_against_per_game",
            field=models.FloatField(
                default=0,
                help_text="The average number of goals scored against the player per game.",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="playerratingnode",
            name="rating_volatility",
            field=models.FloatField(
                help_text="The player's rating volatility for this rating period. This is only used if the rating algorithm is Glicko-2.",
                null=True,
            ),
        ),
    ]
