# Generated by Django 4.2.2 on 2023-07-15 13:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0004_alter_player_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='datetime_played',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='The date and time when the game was played.'),
        ),
    ]
