# Generated by Django 4.2.2 on 2023-07-15 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0005_alter_game_datetime_played'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='event',
            field=models.ForeignKey(default=1, help_text='The event with this game', on_delete=django.db.models.deletion.PROTECT, to='leaderboard.event'),
            preserve_default=False,
        ),
    ]
