# Generated by Django 4.2.2 on 2023-08-18 08:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("team", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
