# Generated by Django 4.2.2 on 2023-07-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("glicko", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="match",
            name="player1_initial_rating",
        ),
        migrations.RemoveField(
            model_name="match",
            name="player2_initial_rating",
        ),
        migrations.AddField(
            model_name="match",
            name="player1_goals_m2",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="The number of goals scored by the first player in second match.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="player1_goals_m3",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="The number of goals scored by the first player in third match.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="player1_goals_m4",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="The number of goals scored by the first player in fourth match.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="player1_goals_m5",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="The number of goals scored by the first player in fifth match.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="player2_goals_m2",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="The number of goals scored by the second player in second match.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="player2_goals_m3",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="The number of goals scored by the second player in third match.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="player2_goals_m4",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="The number of goals scored by the second player in fourth match.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="player2_goals_m5",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="The number of goals scored by the second player in fifth match.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="player1_goals",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="The number of goals scored by the first player in first match.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="player2_goals",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="The number of goals scored by the second player in first match.",
                null=True,
            ),
        ),
    ]
