# Generated by Django 4.2.2 on 2023-07-26 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("glicko", "0002_remove_match_player1_initial_rating_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playerstatsnode",
            name="win_rate",
            field=models.FloatField(help_text="The player's win rate.", null=True),
        ),
    ]
