# Generated by Django 4.2.2 on 2023-07-27 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("glicko", "0003_alter_playerstatsnode_win_rate"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="matchupstatsnode",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterUniqueTogether(
            name="matchupstatsnode",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="matchupstatsnode",
            name="average_goals_against_per_game",
            field=models.FloatField(
                default=0,
                help_text="The average number of goals scored per game by player2.",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="matchupstatsnode",
            name="average_goals_per_game",
            field=models.FloatField(
                default=0,
                help_text="The average number of goals scored per game by player1.",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="matchupstatsnode",
            name="game",
            field=models.ForeignKey(
                default=0,
                help_text="The game which updated the matchup's stats.",
                on_delete=django.db.models.deletion.CASCADE,
                to="glicko.match",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="matchupstatsnode",
            name="games",
            field=models.PositiveIntegerField(
                default=0, help_text="The number of games played by the matchup."
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="matchupstatsnode",
            name="win_rate",
            field=models.FloatField(
                default=0, help_text="player1's win rate against player2."
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="matchupstatsnode",
            name="wins",
            field=models.PositiveIntegerField(
                default=0, help_text="The number of wins the player1 has."
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="matchupstatsnode",
            name="draws",
            field=models.PositiveIntegerField(
                help_text="The number of draws the player1 has."
            ),
        ),
        migrations.AlterField(
            model_name="matchupstatsnode",
            name="losses",
            field=models.PositiveIntegerField(
                help_text="The number of losses the player1 has."
            ),
        ),
        migrations.AlterField(
            model_name="matchupstatsnode",
            name="player1",
            field=models.ForeignKey(
                help_text="The player in the matchup whose perspective to take.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="player1",
                to="glicko.player",
            ),
        ),
        migrations.AlterField(
            model_name="matchupstatsnode",
            name="player2",
            field=models.ForeignKey(
                help_text='The "opponent" player in the matchup.',
                on_delete=django.db.models.deletion.CASCADE,
                related_name="player2",
                to="glicko.player",
            ),
        ),
        migrations.RemoveField(
            model_name="matchupstatsnode",
            name="average_goals_per_game_player1",
        ),
        migrations.RemoveField(
            model_name="matchupstatsnode",
            name="average_goals_per_game_player2",
        ),
        migrations.RemoveField(
            model_name="matchupstatsnode",
            name="draw_percentage",
        ),
        migrations.RemoveField(
            model_name="matchupstatsnode",
            name="games_played",
        ),
        migrations.RemoveField(
            model_name="matchupstatsnode",
            name="loss_percentage_player1",
        ),
        migrations.RemoveField(
            model_name="matchupstatsnode",
            name="loss_percentage_player2",
        ),
        migrations.RemoveField(
            model_name="matchupstatsnode",
            name="player1_wins",
        ),
        migrations.RemoveField(
            model_name="matchupstatsnode",
            name="player2_wins",
        ),
        migrations.RemoveField(
            model_name="matchupstatsnode",
            name="win_percentage_player1",
        ),
        migrations.RemoveField(
            model_name="matchupstatsnode",
            name="win_percentage_player2",
        ),
    ]
