# Generated by Django 4.2.2 on 2023-07-27 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glicko', '0004_alter_matchupstatsnode_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['-date_played']},
        ),
    ]
