# Generated by Django 4.2.2 on 2023-08-01 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("glicko", "0005_alter_match_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="match",
            old_name="player1_goals",
            new_name="player1_goals_m1",
        ),
        migrations.RenameField(
            model_name="match",
            old_name="player2_goals",
            new_name="player2_goals_m1",
        ),
    ]
