# Generated by Django 4.2.2 on 2023-08-19 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glicko', '0008_player_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='formatted_name',
            field=models.SlugField(default=''),
        ),
    ]
