# Generated by Django 4.2.2 on 2023-08-21 08:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("glicko", "0009_player_formatted_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="formatted_name",
            field=models.SlugField(blank=True, default="", unique=True),
        ),
    ]
