# Generated by Django 4.2.2 on 2023-08-24 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("engine", "0005_alter_tournament_org"),
        ("glicko", "0010_alter_player_formatted_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="event",
            field=models.ForeignKey(
                default=False,
                help_text="Event",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="engine.tournament",
            ),
        ),
    ]
