# Generated by Django 4.2.2 on 2023-09-03 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glicko', '0012_player_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='logo',
        ),
    ]
