# Generated by Django 4.2.2 on 2023-09-03 14:55

from django.db import migrations, models
import glicko.models


class Migration(migrations.Migration):

    dependencies = [
        ('glicko', '0014_player_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(help_text="The player's name.", max_length=200, unique=True, validators=[glicko.models.validate_english_name]),
        ),
    ]
