# Generated by Django 4.2.2 on 2023-12-05 06:59

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('glicko', '0015_alter_player_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='logo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='team_logos/logo_fmcs.png', force_format=None, keep_meta=True, quality=-1, scale=None, size=[1920, 1080], upload_to='team_logos/'),
        ),
    ]
